"""removed project metrics table as it can be calculated at runtime

Revision ID: c87ff780d3cb
Revises: fd9da5c6a698
Create Date: 2020-09-27 16:14:25.445311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c87ff780d3cb'
down_revision = 'fd9da5c6a698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_metrics')
    op.alter_column('task', 'expected_completion_date',
                    existing_type=mysql.DATETIME(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'expected_completion_date',
                    existing_type=mysql.DATETIME(),
                    nullable=True)
    op.create_table('project_metrics',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('count', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='project_metrics_ibfk_1'),
                    sa.ForeignKeyConstraint(['status_id'], ['status.id'], name='project_metrics_ibfk_2'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_default_charset='latin1',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###
