"""Added reviewed by column in task table

Revision ID: f9b5093200ab
Revises: c460d77a9806
Create Date: 2020-09-12 23:25:13.000049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9b5093200ab'
down_revision = 'c460d77a9806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.alter_column('task', 'expected_completion_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'task', 'user', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.alter_column('task', 'expected_completion_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('task', 'reviewed_by')
    # ### end Alembic commands ###
